### ISSUE TITLE
Compilation generates errors for stdio.h

### ISSUE THREAD

**Issue by rogermc2** [simonjwright/building-gcc-macos-native#12]
Macbook Air Silicon
OSX 14.7
XCode 16.0

Compilation of  a simple "Hello World" C program produces multiple error messages like:
gprbuild -u -Ptest2.gpr  
Compile
   [C]            test.c
In file included from /System/Volumes/Data/C_Projects/test2/src/test.c:1:
/System/Volumes/Data/Ada_Source/GNAT/gcc-14.2.0-1-aarch64/lib/gcc/aarch64-apple-darwin21/14.2.0/include-fixed/stdio.h:83:8: error: unknown type name ‘FILE’
   83 | extern FILE *__stdinp;
      |        ^~~~
/System/Volumes/Data/Ada_Source/GNAT/gcc-14.2.0-1-aarch64/lib/gcc/aarch64-apple-darwin21/14.2.0/include-fixed/stdio.h:81:1: note: ‘FILE’ is defined in header ‘<stdio.h>’; this is probably fixable by adding ‘#include <stdio.h>’
   80 | #include <sys/_types/_seek_set.h>
  +++ |+#include <stdio.h>

**Comment by simonjwright** [comment]
Apple’s header files are sometimes not standard C, and the GCC build process has a 'fixincludes' phase where fixed-up versions of the header files are inserted before the manufacturer’s.

I’ve reported this, but for the moment I’m afraid the only fix is to revert to the previous Xcode (e.g. 15.3, or 15.4? I use the Command Line Tools).

**Comment by rogermc2** [comment]
Thanks Simon. I had to revert both XCode and Command Line Tools. Now build and runs OK.
