### ISSUE TITLE
Building from scratch on Apple M1

### ISSUE THREAD

**Issue by joelreymont** [simonjwright/building-gcc-macos-native#4]
How do I build GNAT FSF from scratch on Apple M1?

The instructions in the README seem to require me to have a toolchain already, e.g. gprbuild.

**Comment by simonjwright** [comment]
A high proportion of GCC’s Ada compiler is written in Ada, so the base compiler has to understand Ada already. Best to use the previous release, though you might be lucky with earlier ones.

Gprbuild is not required.

If you want to build for aarch64 (Apple silicon), you need to use the appropriate source, which hasn’t yet been merged with the official GCC source (though it’s very close), [here](https://github.com/iains). You can use one of my aarch64 compilers, or you could start with an x86_64 compiler, build a cross compiler (under Rosetta), and use that to build an aarch64 compiler (as with [this tag](https://github.com/simonjwright/building-gcc-macos-native/tree/gcc-12.2.0-aarch64)).

**Comment by joelreymont** [comment]
And thank you Simon for your great work this the Apple Silicon builds!
