### ISSUE TITLE
Link error on Sonoma 14.1 with Apple Silicon

### ISSUE THREAD

**Issue by juergenpf** [simonjwright/building-gcc-macos-native#5]
Compiling a simple program results in an error during gnatlink phase. Here is the output:

-macosx_version_min has been renamed to -macos_version_min
ld: warning: ignoring duplicate libraries: '-lgcc'
0  0x104e73648  __assert_rtn + 72
1  0x104da7fac  ld::AtomPlacement::findAtom(unsigned char, unsigned long long, ld::AtomPlacement::AtomLoc const*&, long long&) const + 1204
2  0x104dbd924  ld::InputFiles::SliceParser::parseObjectFile(mach_o::Header const*) const + 15164
3  0x104dcb04c  ld::InputFiles::parseAllFiles(void (ld::AtomFile const*) block_pointer)::$_7::operator()(unsigned long, ld::FileInfo const&) const + 960
4  0x18414b950  _dispatch_client_callout2 + 20
5  0x1841601a4  _dispatch_apply_invoke_and_wait + 176
6  0x18415f464  _dispatch_apply_with_attr_f + 1176
7  0x18415f650  dispatch_apply + 96
8  0x104e453b8  ld::AtomFileConsolidator::parseFiles(bool) + 292
9  0x104de6170  main + 9048
ld: Assertion failed: (resultIndex < sectData.atoms.size()), function findAtom, file Relocations.cpp, line 1336.
collect2: error: ld returned 1 exit status
gnatlink: error when calling /opt/gcc-13.1.0-aarch64/bin/gcc
gnatmake: *** link failed.

**Comment by simonjwright** [comment]
So sorry, didn’t see this.

For me, I’ve installed the Command Line Tools 15.1 beta (either 1 or 2 should do the trick).

**Comment by juergenpf** [comment]
Thx, that did the trick:-)
